name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Vet
        run: go vet ./...
      - name: Run linter
        uses: golangci/golangci-lint-action@v3