name: Tests

on:
  workflow_call:

jobs:
  test:
    name: "Test: go v${{ matrix.go-version }}"
    strategy:
      matrix:
        go-version:
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -v -race $(go list ./... | grep -v '/examples/')